service: chapman-skate

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  profile: fgm-dev

custom:
  s3BucketName: chapman-skate

package:
  include:
    - node_modules
    - src/functions
    - lambda.js

functions:
  get-stream:
    handler: lambda.getStream
    events:
      - http: GET /get-stream
  get-boards:
    handler: lambda.getBoards
    events:
      - http: GET /get-boards

resources:
  Resources:
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3BucketName}
        WebsiteConfiguration:
          IndexDocument: index.html
    CloudfrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
          - DomainName: ${self:custom.s3BucketName}.s3.amazonaws.com
            Id: myS3Origin
            S3OriginConfig:
              OriginAccessIdentity: ''
          Enabled: 'true'
          DefaultRootObject: index.html
          DefaultCacheBehavior:
            TargetOriginId: myS3Origin
            ForwardedValues:
              QueryString: 'true'
              Cookies:
                Forward: none
            ViewerProtocolPolicy: allow-all
          PriceClass: PriceClass_100
